### ISSUE TITLE
Change homepage to use hard-coded file names

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#255]
In order to process the images properly, we need to be able to match on them.

Right now, we allow any image name (relative to the event's source) to be set in that parameter. 

I suggest instead we require it to be named `logo_square.jpg` and placed in that directory. We can add a boolean for `event_logo` which is set to `default` if they don't want to make one.

**Comment by bridgetkromhout** [comment]
I'm on board with this change.

**Comment by mattstratton** [comment]
Remind me, what is the workflow for a new event? They are prompted for this image, right?

**Comment by mattstratton** [comment]
This is probably more of a documentation fix in the README for how you set a square homepage logo.

**Comment by bridgetkromhout** [comment]
We want people to be able to get started with a new event without having to have already created artifacts. So, we deliberately don't prompt for a logo image during event creation, since almost nobody with a enw event has one ready. We do mention it in the README: https://github.com/devopsdays/devopsdays-theme/blame/master/exampleSite/utilities/README.md#L17


_Once you have created a logo graphic, place it in static/events/yyyy-city/logo.png. (The file MUST be called logo.png.) The sample welcome page has a commented-out element to display a logo named in this way. For front-page use, you also need a square version in static/events/yyyy-city/logo-square.jpg (url configurable in your datafile)._

We should probably resolve the png versus jpg thing here just to prevent confusion. (We switched to requiring jpg for the square one - we should either require jpg for both, or not have a requirement for the more free-form logo that is just displayed on the front page.)

**Comment by bridgetkromhout** [comment]
Bridget to consider name of toggle and to update README.

**Comment by mattstratton** [comment]
I am adjusting this to now look for a specific filename. The event logo for the homepage must be in the `static/YYYY-CITY` directory, and be named `logo-square.jpg`.

Otherwise it will display the brain logo.

We need to go back through the event data files and remove the unneeded `event_logo_square` key. It doesn't harm anything being there, other than being confusing.
