### ISSUE TITLE
fix the sharing card so all text is readable

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#434]
### Expected behavior

People would be able to read, at minimum, the word "devopsdays". Ideally, the sharing image would be shifted over so the text is readable and there are fewer "brain" gears in the sharing field of vision.

### Actual behavior

Possibly because of it choosing the center of the image, we see lots of the "brain" gears but little of the text.

![screen shot 2017-03-27 at 8 56 12 am](https://cloud.githubusercontent.com/assets/2104453/24359931/6c866176-12cb-11e7-9470-8a5a23453d26.png)

### Reproduction Steps

Share the URL https://www.devopsdays.org on Twitter and go look at the tweet in the browser.

**Comment by mattstratton** [comment]
I think this is because we don't set a sharing card for twitter; twitter cards are really tough because their rules are that the URL has to be about content, not about a website or whatever. 

This is the type of card we want to create: https://dev.twitter.com/cards/types/summary-large-image

This was the issue I ran into when trying to do this (we can decide if it applies to us or not):

```
A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size.
```

I suppose since we are doing an image that is for the event, it would work out okay...

**Comment by mattstratton** [comment]
[Prodpad idea](https://portal.prodpad.com/24442/ideas/364320)

**Comment by mattstratton** [comment]
I'm re-opening this until we can validate it after the merge of #437

**Comment by mattstratton** [comment]
Tested and this is fixed in master
