### ISSUE TITLE
Extra space in welcome pages 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#472]
![img_3896](https://cloud.githubusercontent.com/assets/1280666/24688504/60cdfa8c-198e-11e7-8c9a-059379946a73.PNG)
### Reproduction Steps
Look at the Atlanta home page

**Comment by jduv** [comment]
I'm not a hugo short code expert, but it appears this issue is due to how the event code is rendering the corresponding HTML (which looks pretty nasty). If I modify the content in DevTools I can fix the problem. 

Busted:
<img width="479" alt="issue472 busted" src="https://cloud.githubusercontent.com/assets/591405/24689837/44c7a30c-1997-11e7-93e3-e372937c12d5.png">

Hand fixed:
<img width="482" alt="issue472 hand fixed" src="https://cloud.githubusercontent.com/assets/591405/24689824/3ec1dfa4-1997-11e7-8cbd-6a782833d841.png">

**Comment by mattstratton** [comment]
FWIW, this was the part that fixes it:

https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/shortcodes/event_location.html#L4

Basically, if you put a `-` on either end of the `{{` or `}}`, then Hugo won't render a newline.

**Comment by mattstratton** [comment]
It would be made even prettier if we did this:

```
{{- $path := split .Page.Source.File.Path .Site.Params.PathSeparator -}}
{{- $event_slug := index $path 1 -}}
{{- $e :=  (index .Page.Site.Data.events $event_slug) -}}
```

**Comment by mattstratton** [comment]
See fix here https://dev.devopsdays.org/events/2017-atlanta/welcome/
