### ISSUE TITLE
Add 'workshop' as a new layout type to theme

### ISSUE THREAD

**Issue by yvovandoorn** [devopsdays/devopsdays-theme#486]
### New feature
Allow 'workshop' to be a layout, just like 'talk'. This allows speaker to have a workshop and talk, and also have the material be separate as the 'talk' layout has 'talk' specific language.

**Comment by mattstratton** [comment]
So @bridgetkromhout and I were talking this through, and want to make sure we understand the needfulness of this change.

WRT to "having a speaker give a talk and a workshop", there is nothing in the logic that prevents you from naming the file `matt-stratton-workshop.md` for the workshop and `matt-stratton.md` for the talk. So that particular use case doesn't require this.

The second part, about having talk-specific stuff in the template makes more sense to me. Also if you were going to somehow eventually have some kind of template for a list of workshops only?

**Comment by mattstratton** [comment]
Based upon #554, this issue isn't needed anymore.
