### ISSUE TITLE
Social button don't show for a speaker in the talk page

### ISSUE THREAD

**Issue by technovangelist** [devopsdays/devopsdays-theme#582]
### Expected behavior
I would expect the talk page to show all the social icons for the speaker that the speaker page does. 
### Actual behavior
The talk page shows the twitter link only. the speaker page shows all the links

**Talk page**
![image](https://user-images.githubusercontent.com/633681/28630278-e4a9501a-71f7-11e7-8ca0-24d921c2776b.png)

**Speaker page**
![image](https://user-images.githubusercontent.com/633681/28630302-f4b39c0e-71f7-11e7-8d51-0e1c09385ac6.png)

### Reproduction Steps
add a speaker and talk and add some social links
### Operating System and Version
NA
### Web Browser and Version
NA

**Comment by bridgetkromhout** [comment]
Yes, additional speaker info can be found on their speaker-specific page. Twitter handle being available on the talk page is to assist with livetweeting (which needs that specific info quickly). In my opinion, we don't need all available in-depth speaker info on the talk page. This is a deliberate choice on my page. I am fine with @mattstratton overruling me if he thinks the talk pages would benefit from being busier; I don't think they would. (Upon further consideration, I actually think the full speaker bios are too long for the talk pages too.)

**Comment by mattstratton** [comment]
I am totally fine (and would actually argue for) with having the bio on the talk page. I don't like having too many clicks back and forth; I think that the bio goes with the talks for sure.

I personally don't find the additional social icons to make the talk page that much busier, but since I recall Bridget making a change since it bothered her, I'll go back to her thought on that. 

The less clicking someone has to do in order to find information the better, which is why collapsing as much into a single page (even if it's redundant) isn't bad. yes, the bio shows up on the speaker page AND the talk page, but for the end user, they don't even really know that they should go to the speaker's page. And I am not 100% sure we even have a click target for the speaker on the talk page (maybe it's the image; I don't remember).

**Comment by technovangelist** [comment]
since its one set on one page and a subset on the other page, it felt like a mistake.

**Comment by bridgetkromhout** [comment]
Hi, @technovangelist - in reviewing https://github.com/devopsdays/devopsdays-theme/pull/620 I am pretty sure this issue is resolved. Please let us know if there's anything that's still needed. Thanks!
