### ISSUE TITLE
document how logo-square is not wysiwyg or make it wysiwyg

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-theme#590]
### Expected behavior

In the deploy preview on Netlify, I expect that the layout of the front-page logo squares will look exactly the same as the result I'll get after a deploy.

### Actual behavior

Ignore the sort-order problem here, as I'm pretty sure it's orthogonal to the layout problem. What I think is happening is, if the logo square is not actually square, we see the problem before the processing pipeline but it's fixed in processing.

<img width="798" alt="screen shot 2017-08-30 at 7 45 48 am" src="https://user-images.githubusercontent.com/2104453/29873245-47dcf404-8d58-11e7-8bac-301b92410168.png">

Versus
<img width="778" alt="screen shot 2017-08-30 at 7 53 22 am" src="https://user-images.githubusercontent.com/2104453/29873273-5aa975b2-8d58-11e7-8522-1e48ac407188.png">

### Reproduction Steps

Look before and after the deploy at Nashville.

If this is unavoidable, then let's document it somewhere such as https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#event-square-logo or https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md

**Comment by mattstratton** [comment]
Yeah, unless we want to run the image processing pipeline on every deploy preview (which we probably don't, since it takes 2-3 minutes at least), you're going to get this happening. It happens locally too; not just deploy previews. 

It's probably worth documenting what happens during a production deploy so there aren't surprises.

**Comment by bridgetkromhout** [comment]
Yeah, I figured that was the answer. I think we should make it explicit so people aren't confused when what you see is not what you get. And maybe could we give a command-line switch that a) warns it will take a while and b) requires whatever tools to exist locally but then will produce a perfect wysiwyg local option?

**Comment by mattstratton** [comment]
> And maybe could we give a command-line switch that a) warns it will take a while and b) requires whatever tools to exist locally but then will produce a perfect wysiwyg local option?

Oof. That's really complex. Mostly because it won't work with the local `hugo server` option; it builds static files that have to be served by something else. It's just really not that easy to do.

I have a to-do at some point to move the CSS generation and javascript uglification/combination out of codekit (which nobody has but me) into gulp; when I do that I will probably be able to make a gulp task that includes watch which will fire up a tiny web server for being able to see things live, at which point we can include this type of thing. I don't really know if it's that big of a deal for the amount of effort that will take; this only comes up if people aren't following the standards anyway, which means they didn't read the docs, which means what good is it to document it further with more complexity?

**Comment by mattstratton** [comment]
Once we get #507 and #632, it will be easier to put instructions in on how to run the full pipeline locally, including a `watch` task, if people really want WYSIWYG.

**Comment by bridgetkromhout** [comment]
>  I don't really know if it's that big of a deal for the amount of effort that will take; this only comes up if people aren't following the standards anyway, which means they didn't read the docs, which means what good is it to document it further with more complexity?

We document that it must be square. I've now clarified what that should mean. I'm going to resolve this as good enough. I don't think a local wysiwyg build is essential.
