### ISSUE TITLE
Add "event_group" optional key to event data file

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#61]
This will allow for past events whose city name doesn't match the current one to be listed in the "past events" list.

**Comment by mattstratton** [comment]
After further review, it seems this is better handled by adding an `event_group` optional key, which is then added to all current and past events of the group.

The "Past events in..." logic in the Welcome page needs to check for this and override it.

Also, change the grammer in "Past events in..." to "Past THING events..."

**Comment by mattstratton** [comment]
So we will add an optional key called `event_group`, and if it is set, it will override the "Past DENVER events" to "Past ROCKIES events" or whatever.

**Comment by bridgetkromhout** [comment]
See https://github.com/devopsdays/devopsdays-theme/blob/master/layouts/partials/welcome.html#L38

**Comment by bridgetkromhout** [comment]
This says it was added to Backlog but it's also still in the v1.0 release - please clarify? I think this is nice but not essential for the first release.

**Comment by mattstratton** [comment]
"Added to backlog" is from the stupid GH project that I can't get rid of. 

Trust milestones. I would say move this to 2.0 milestone.

**Comment by bridgetkromhout** [comment]
Okay, cool. I moved it.

**Comment by bridgetkromhout** [comment]
Okay, since this affects the New York City event in a few weeks, I figured now is the time to put a fix in place.

Use cases that don't change:
* An event's first year (whether or not event_group is set): no "other events" will be shown

<img width="654" alt="screen shot 2017-12-28 at 1 05 57 pm" src="https://user-images.githubusercontent.com/2104453/34420888-a7e7b0c8-ebd1-11e7-9870-55d878e4a11d.png">


* No event_group set and there are multiple years: shows the same "other events" it did before

<img width="702" alt="screen shot 2017-12-28 at 1 05 48 pm" src="https://user-images.githubusercontent.com/2104453/34420881-a2f28c00-ebd1-11e7-9bad-df1e2f8167b9.png">


Use case that changes:
* Event_group set and there are multiple years: now shows "other events" that have the same event group.

Before:

<img width="726" alt="screen shot 2017-12-28 at 1 19 24 pm" src="https://user-images.githubusercontent.com/2104453/34420908-c9262116-ebd1-11e7-81f6-7eea48ef02c3.png">


After:

<img width="738" alt="screen shot 2017-12-28 at 1 05 33 pm" src="https://user-images.githubusercontent.com/2104453/34420878-9ba1b19c-ebd1-11e7-9125-b7870c7d2185.png">

Pull request for theme fix: https://github.com/devopsdays/devopsdays-theme/pull/614
