### ISSUE TITLE
Add optional "Event Name" parameter to yyyy-city data file

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#62]
Some events are not named after the city, so there should be an optional parameter called `event_name` which over-rides the city name if it is set.

**Comment by bridgetkromhout** [comment]
I would rather focus on https://github.com/devopsdays/devopsdays-theme/issues/61 to let events be linked rather than confusing people with "This is devopsdays Midwest, Minneapolis Edition. Next month will be devopsdays Midwest, Chicago Edition". In general I do _not_ want to encourage non-city names.

**Comment by mattstratton** [comment]
Closing this in favor of #61
